[FIX] beauty_parlor: prevent error when opening the Contact Us page
Currently, an error occurs when opening the Contact Us page.

Steps to Reproduce:

 - Install the beauty_parlor with demo data.
 - Go to Website > Contact Us.

ValueError: Element '<xpath expr="//section[@data-snippet='s_title'][1]/span">' cannot be located in parent view

This error started occurring in saas-19.1 after [commit] that reworked
the Contact Us page to better showcase the capabilities of the website
builder. As part of that change, the section was modified, but the code
still references an XPath [1] that no longer exists in the main view.
As a result, opening the Contact Us page raises this error.

This commit replaces the default website aside image with a beauty
parlor related image, similar to what was done [here], since the banner
is no longer used in the main view.

[1]: https://github.com/odoo/industry/blob/22cac5a9fc54f33ed99fd924c962b35f4bd5f1f5/beauty_parlor/demo/website_view.xml#L8-L10

[here]: https://github.com/odoo/industry/commit/de71da8c58b89e95d2ac55b277accdc7490cb68f

sentry-7336372498

closes odoo/industry#2461

Signed-off-by: Vallaeys Valentin (vava) <vava@odoo.com>