[REM] guided_tours: remove record linked to deleted template
Currently an exception is generated when the user tries to open any
appointment after installing `Guided Tours` industry with the demo data.

Error: `Element '<xpath expr="//a[@t-if='len(available_appointments) ...`

This occurs because the component referenced in the XPath expression
was removed in saas-19.1 by commit [1], while it is still being used
in the industry module's XPath.

This commit removes this record id `ir_ui_view_3838` because the
`appointment_progress_bar` template was completely removed in commit [1].

[1]: https://github.com/odoo/enterprise/commit/28ea0b18d5bc2dbd6a9d7544d3cca2a60e89be40

Sentry-7210263230

X-original-commit: f44fb8d393ee48da17d36a976ea5e3bf10f7afa5