[FIX] booking_engine: prevent error when unscheduling a planning slot
Currently, an error occurs when user unschedule a planning slot.

Steps to Reproduce:
 - Install the Hotel module.
 - Create a product of type Service.
 - Create a sales order and add this product to a sales order line and
   confirm it.
 - Open the recently created product, enable Plan Services, and select a role.
 - Go to Planning and create a new planning slot.
 - And select the recently created sales order in Sales Order Item.
 - Clear the Start Date and End Date.
 - Select the planning slot and click Unschedule.

ValueError: AttributeError("'bool' object has no attribute 'astimezone'") while evaluating
'pickup_time = env.ref(\'sale_renting.recurrence_nightly\').pickup_time\nreturn_time = env.ref(\'sale_renting.recurrence_nightly\').return_time\ntz = env.ref(\'website.default_website\').tz\nfor record in records:\n    if not record.role_id.x_is_a_room_offer: continue\n    ..........

Cause:
 - When the user clicks Unschedule, the start and end dates are set to
   False [1]. After that, the Fix Slot Times server action is executed and
   raises an error at [2].
 - If the start and end dates are False and the product linked to sale_line_id
   has planning_enabled enabled, these start and end date fields are no
   longer required [3].

Fix:
 - This commit ensures that when there is no start and end date, the
   computation of the start and end dates is skipped, since both fields
   are False at the same time.

[1]: https://github.com/odoo/enterprise/blob/63cc9f15c3be14b3208c84c7c5221936ae7e3f12/sale_planning/models/planning_slot.py#L684-L688

[2]: https://github.com/odoo/industry/blob/604834df2e589e4c3281784292b9357592fa2615/booking_engine/data/ir_actions_server.xml#L37-L38

[3]: https://github.com/odoo/enterprise/blob/63cc9f15c3be14b3208c84c7c5221936ae7e3f12/sale_planning/views/planning_slot_views.xml#L35-L42

sentry-7229364722