[FIX] headhunter: prevent error on opening jobs page
Currently an error occurs when user opens job page in website

Steps to replicate:
* Install headhunter with demo data
* Open website> Jobs

Error:
`ValueError:
Element '<xpath expr='//ul[hasclass('o_jobs_topbar_filters')]'>' cannot
be located in parent view`

Root cause:
After commit [1], the class o_jobs_topbar_filters was removed, but references to
it remain in the XPath expressions. This causes an error when opening the Jobs
page.

Solution:
* Use standard templates instead of redefinition of templates.

[1]:
https://github.com/odoo/odoo/commit/9a267abb9afe7d973808928cfcd62cd48f0e77c8

sentry-6780953032

X-original-commit: 421fcdb94ac8857fa4e9c6ea7ade4573bf1ecb9e