[FIX] *: prevent error when accessing the event page
*: gallery, guided_tours, night_clubs

Currently, an error occurs when a user accesses the event page on the website.

Steps to Reproduce:
 - Install the gallery with demo data.
 - Go to Website > Events.

ValueError: Element '<xpath expr="//section[hasclass('o_wevent_index_topbar_filters')]/h1[hasclass('me-auto')]">' cannot be located in parent view

After the [recent commit], which improved the font style changes for
the <h1> element in the website editor, the <h1> element was modified.
However, the code still references an XPath [1] that no longer exists
in the main view. As a result, opening the event page raises an error.
The same error also occurs in the guided_tours [2] and night_clubs [3]
industries.

This commit ensures that the correct XPath is used in the gallery,
guided_tours, and night_clubs event pages.

[recent commit]: https://github.com/odoo/odoo/commit/9d04d4d35ffdc4bbe4b6bb8c1c950697c71be95d

[1]: https://github.com/odoo/industry/blob/917876b4d62a7d0ff05706928b672171a4f0a1c9/gallery/demo/website_view.xml#L374-L378

[2]: https://github.com/odoo/industry/blob/917876b4d62a7d0ff05706928b672171a4f0a1c9/guided_tours/demo/website_view.xml#L217-L219

[3]: https://github.com/odoo/industry/blob/917876b4d62a7d0ff05706928b672171a4f0a1c9/night_clubs/demo/website_view.xml#L340-L343

sentry-7609379255

closes odoo/industry#2568

Signed-off-by: Vallaeys Valentin (vava) <vava@odoo.com>