[FIX] guided_tours: prevent error when accessing the Book a Guide page
Currently, an error occurs when a user accesses the Book a Guide page
on the website.

Steps to Reproduce:

 - Install guided_tours with demo data.
 - Go to Website > Book a Guide.

 ValueError: Element '<xpath expr="//section[hasclass('d-flex')]/h1[hasclass('me-auto')]">' cannot be located in parent view (view: guided_tours.website_calendar_index_topbar)

After the [recent commit] , the root <h1> was wrapped in a <div> so that
Font Style changes apply correctly to controller page headings. However,
the code still references an XPath [2] that no longer exists in the main view.
As a result, opening the book a guide page
raises an error.

This commit updates the XPath in the guided tours view to match the
parent template structure.

[recent commit]: https://github.com/odoo/enterprise/commit/8477b72987a6ed49c0294e75196249af9442b3ab

[2]: https://github.com/odoo/industry/blob/37de4d74ab0ae4c5b9cf206ac5cf9c2738d8ce18/guided_tours/demo/website_view.xml#L229-L231

[1]: https://github.com/odoo/enterprise/blob/56835e15df6b39200cd1da185e04dc09c2f24aef/website_appointment/views/appointment_templates_appointments.xml#L78-L80

sentry-7609379255

X-original-commit: 16e528e5803acf08bb3fc0ea03107fd596a890b4