[FIX] condominium, property_assets_distribution: fix error on property deletion
Currently, an error occurs when a user deletes a property record.

Steps to Reproduce:
 - Install industry_real_estate with demo data.
 - Go to Leasing > Properties > Properties.
 - Delete a property record.

ValueError: AttributeError("'x_property' object has no attribute 'x_owner_ids'") while evaluating
"record.x_owner_ids.x_account.write({'active': False})"

After a [recent commit], the x_owner_ids field was defined on x_property
in the condominium module [1]. The error occurs when a property record is
deleted and a server action [2] is triggered through a base automation rule [3]
to archive the owners' account records. Since x_owner_ids is defined in
the condominium module, accessing it raises an error when the condominium
module is not installed.

This commit moves the server action and the corresponding base automation
rule to the condominium module, where the x_owner_ids field is defined.

[recent commit]: https://github.com/odoo/industry/commit/8e166b3bb8bb66e53da5c2f9e6e15a9751f7aa38#diff-70ae8e6ca07f28b93f3e4d02c124d0217e4e951b2b5f77a92cc9651142c22c0d

[1]: https://github.com/odoo/industry/blob/d0b2141b47115dc8dd7a5e5fca4131a227125435/condominium/data/ir_model_fields.xml#L200-L208

[2]: https://github.com/odoo/industry/blob/d0b2141b47115dc8dd7a5e5fca4131a227125435/property_assets_distribution/data/ir_actions_server.xml#L47-L55

[3]: https://github.com/odoo/industry/blob/d0b2141b47115dc8dd7a5e5fca4131a227125435/property_assets_distribution/data/base_automation.xml#L10-L15

sentry-7511045457