[FIX] corporate_gifts: prevent error on record not found
This error occurs when we try to open the 'Contact Us' page on the website
without the 'Others' tag, which the view expects and fetches directly.

Steps to reproduce:
- Install 'corporate_gifts' module (demo data)
- Open 'Contact Us' or 'Request a Quote' in website

Traceback:
ValueError: External ID not found in the system: sales_team.categ_oppor8

QWebError
Error while rendering the template:
    ValueError: External ID not found in the system: sales_team.categ_oppor8
    Template: website.contactus
    Reference: 1879
    Path: /t/t/div/section[2]/div/div/div[1]/section/div/form/div/div[8]/div/div/div/div[5]/div/input
    Element: <input type="checkbox" class="s_website_form_input form-check-input" id="osinp1mz79g4" name="tag_ids" t-att-value="request.env.ref(\'sales_team.categ_oppor8\').id"/>
    From: (1879, '/t/t', '<t t-call="website.layout"/>')
          (1879, '/t/t/div/section[2]/div/div/div[1]/section/div/form/div/div[8]/div/div/div/div[5]/div/input', '<input type="checkbox" class="s_website_form_input form-check-input" id="osinp1mz79g4" name="tag_ids" t-att-value="request.env.ref(\\\'sales_team.categ_oppor8\\\').id"/>')

At [1], we directly fetch a record from sales_team, but this record is created
only in demo data. If the crm module is installed without demo data, that
record will not exist. As a result, when corporate_gifts (which includes
demo data) is installed and we open the website, an error occurs.

[1]- https://github.com/odoo/industry/blob/218eace0db41df929787d7fbbc7549d5a1733591/corporate_gifts/data/website_view.xml#L146

sentry-7033973232

X-original-commit: 265da163ea3786d4ce4c38ab79c7cf8575979403