[FIX] booking_engine: prevent error when creating a planning slot record
Currently, an error occurs when the user creates a planning slot record.

Steps to Reproduce:

 - Install the booking_engine module without demo data.
 - Go to Sales Orders, create a sale order with a product of type Service,
   and confirm the sale order.
 - Go to Planning > Open Shifts > switch to the List view.
 - Click New, add the sale order in the line, remove the start and end dates,
   and then click anywhere.

ValueError: AttributeError("'int' object has no attribute 'total_seconds'") while evaluating "\nfor record in self: record['x_nights'] = ((record.end_datetime - record.start_datetime).total_seconds() + 86399) // 86400\n

This error occurs when the user creates a planning slot record and removes
the start and end dates. When the compute method tries to calculate the
Nights for that record, the start and end dates are False, and subtracting
them results in 0, which raises an AttributeError when accessing
total_seconds [1].

This commit ensures that nights are computed only when both the start and
end dates are present; otherwise, it is set to 0.

[1]: https://github.com/odoo/industry/blob/1b4b845b946d6272c967efddd519b5bda773b443/booking_engine/data/ir_model_fields.xml#L184

sentry-7046331723

X-original-commit: 05eccca379af215b443bfd8b2366592744595a06