[FIX] gallery,micro_brewery: prevent error on opening product page
Currently an error occurs when opening product page on website.

Steps to replicate:
* Install micro_brewery with demo data
* Website > Shop > Open any product

Error:
ValueError: Element'<xpath expr='//div[@id='o_product_terms_and_share']'>'
cannot be located in parent view

Root cause:
After commit [1], the div at [2] was removed, but the demo data XPath
expressions in the gallery and micro_brewery modules still reference it,
causing errors.

Solution:
* Modify the xpath template to match with the updated code.

[1]:
https://github.com/odoo/odoo/commit/bbb2d98d9ab97ce729d59b9858b63daccf5434e2#diff-635040c730ccbb8e4f6f2bf6472cf48a0cc9b8a3d488289dabdfce8096811915L2078

[2]:
https://github.com/odoo/odoo/blob/981a3f7afef6bf321b956b85e453ba85b83e43ed/addons/website_sale/views/templates.xml#L1884-L1887

sentry-6781422394

closes odoo/industry#1043

X-original-commit: cfcd34f3b2dc66710f554e15c2dd1b72ba5ab060
Signed-off-by: Vallaeys Valentin (vava) <vava@odoo.com>