[FIX] spa_resort: prevent erorr when opening contact us page
Currently, an error occurs when the user opens the Contact Us page.

Steps to Reproduce:
 - Install the spa_resort with demo data.
 - Go to Website > Contact Us.

ValueError: Element '<xpath expr="//t[@t-name='website.contactus']//span[hasclass('s_parallax_bg')]">' cannot be located in parent view

The error starts occurring from saas-19.1 because, after [this commit]
where the Contact Us page was reworked to better showcase the capabilities
of the website builder, the span element was replaced, but the code
still references an XPath [1] that was removed from the main view. As
result, opening the Contact Us page raises this error.

This commit replaces the default website aside image with a spa resort
related image, as the banner is no longer used in the main view.

[this commit]: https://github.com/odoo/odoo/commit/ba8d1f60b82ffeada0b222481706a5c65623020d#diff-409cc7362c7557970ce7506fc9a1097c37c7869b7cd815ce463db38a3b7a8239

[1]: https://github.com/odoo/industry/blob/bdbdd15f11f3304f192f44a7baf0743520ba8ae6/spa_resort/demo/website_view.xml#L308-L309

[2]: https://github.com/odoo/odoo/blob/072a8e4fd061ff23902e6e448a577624cb27e188/addons/website/data/website_data.xml#L35-L36

sentry-7336372498