[FIX] elearning_platform: prevent error while opening Courses page
Currently, an error is generated when the user tries to open
the``Courses (/slides)` page after installing `elearning_platform`
Industry with the demo data.

Error:
```
QWebError
Error while rendering the template:
    TypeError: can only concatenate str (not "NoneType") to str
```

This issue is caused by a recent refactoring introduced after commit [1], where
the syntax of `t-call` was updated. Previously, variables were passed using the
`t-set` element, but now they are passed directly as `attributes` of `t-call`.

However, in the `elearning_platform` industry module, the old `t-call` syntax
is still being used. Specifically, the `redirect_url` value is defined inside a
`t-set` block. As a result, when the called template tries to access
 `redirect_url` at [2], it is not received correctly and ends up being `None`.

This commit resolves the issue by updating the implementation to follow
the new `t-call` syntax, ensuring that variables are passed as attributes
instead of using the `t-set element`.

[1]: https://github.com/odoo/odoo/commit/bba2fc505f5d0b4770eacc6877155b1aeda6d772
[2]: https://github.com/odoo/odoo/blob/051cb38646cab2354a6176a2d020d9d286147c68/addons/website_profile/views/website_profile.xml#L562

Sentry-7325420786

closes odoo/industry#1872

X-original-commit: 38cc7b15a5ebfa9258072de8d29337a7df68a37a
Signed-off-by: Vallaeys Valentin (vava) <vava@odoo.com>