[FIX] 3pl_logistic_company: prevent error when running schedule action
Currently an error occurs when executing the Stock History-Create Daily
Records scheduled action.

Steps to Reproduce:

 - Install the 3pl_logistic_company module.
 - Go to Scheduled Actions and run the Stock History-Create Daily Records
   action.

ValueError: Invalid operator in condition ('inventory_quantity_auto_apply', '>;', 0.0)

This error occurs due to the use of the HTML-escaped operator > in the
domain [1], which raises an error when the scheduled action runs.
Additionally, inventory_quantity_auto_apply is a computed, non-stored field,
so searching on it causes an error.

This commit replaces the escaped operator > with the correct operator
'>' and filters the records based on inventory_quantity_auto_apply.

[1]: https://github.com/odoo/industry/blob/8b6b1066ec7dad6c82368dbdc61110dbc07f01e4/3pl_logistic_company/data/ir_cron.xml#L11

sentry-7004609305